name = "ido-project"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat", "nodejs_compat_eol"]

[env.production]
compatibility_flags = ["nodejs_compat", "nodejs_compat_eol"]

[env.preview]
compatibility_flags = ["nodejs_compat", "nodejs_compat_eol"]
